
[Interface]
Address = 10.101.0.14/32
PrivateKey = 6CFvTFKjpNXGvZ5UuiKXdextF4XTti6UdMFG8Q6YGUw=
PostUp = printf 'You can now access http://0.0.0.0:82 on https://q4x6v3.tunnel.pyjam.as/ ✨\n'

[Peer]
PublicKey = 51I3l3Jxvb86K0PkvxolHX4c0XhDPYczyjAxm6XG+Cc=
AllowedIPs = 10.101.0.1/32
Endpoint = tunnel.pyjam.as:55555
PersistentKeepalive = 21
